# Generated by Django 5.1.7 on 2025-04-09 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время публикаций')),
                ('edited', models.BooleanField(default=False, verbose_name='редактирован ли ?')),
            ],
        ),
    ]
