# Generated by Django 5.2 on 2025-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='name of picture'),
        ),
    ]
