# Generated by Django 5.1.7 on 2025-05-04 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_postattachments_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postattachments',
            name='image',
            field=models.ImageField(upload_to='files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postattachments',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Редактирован ли?'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время публикации'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy')),
            ],
        ),
    ]
